export const guestsArray = [
  {
    id: 1,
    name: 'Bobby',
    email: 'bobby@gmail.com',
    plusone: 1,
    plusone_Name: 'Summer',
    dietary: 'none',
    rsvp: 1,
    event_id: 1,
    table_Number: 1,
  },
  {
    id: 2,
    name: 'Jack',
    email: 'jack@hotmail.com',
    plusone: 1,
    plusone_Name: 'Mary',
    dietary: 'vegan',
    rsvp: 1,
    event_id: 1,
    table_Number: 1,
  },
  {
    id: 3,
    name: 'Dracula',
    email: 'dracula@hotmail.com',
    plusone: 0,
    plusone_Name: '',
    dietary: 'gluten-free',
    rsvp: 0,
    event_id: 1,
    table_Number: 2,
  },
  {
    id: 4,
    name: 'Erlich',
    email: 'erlich@gmail.com',
    plusone: 0,
    plusone_Name: '',
    dietary: 'pesca-pescatarian',
    rsvp: 1,
    event_id: 1,
    table_Number: 3,
  },
  {
    id: 5,
    name: 'Taika',
    email: 'taika@gmail.com',
    plusone: 0,
    plusone_Name: '',
    dietary: 'none',
    rsvp: 0,
    event_id: 1,
    table_Number: 1,
  },
]
